const express = require('express')
const apiRoute = express()
const UserRouter = require('../apps/user/user-router')
const CartRouter = require('./../apps/cart/cart-router')
const CouponRouter = require('./../apps/coupon/coupon-router')
const FavoriteRouter = require('./../apps/favorite/favorite-router')
const OrderRouter = require('./../apps/order/order-router')
const PaymentRouter = require('./../apps/payment/payment-router')
const UserAddressRouter = require('../apps/user_address/user-address-router')
const MealRouter = require('./../apps/meal/meal-router')
const CategoryRouter = require('./../apps/category/category-router')
const AuthRouter = require('./../apps/auth/auth-router')

apiRoute.use('/meals', MealRouter)
apiRoute.use('/carts', CartRouter)
apiRoute.use('/coupons', CouponRouter)
apiRoute.use('/favorites', FavoriteRouter)
apiRoute.use('/orders', OrderRouter)
apiRoute.use('/payments', PaymentRouter)
apiRoute.use('/user-addresses', UserAddressRouter)
apiRoute.use('/categories', CategoryRouter)
apiRoute.use('/users', UserRouter)
apiRoute.use('/auth', AuthRouter)

module.exports = apiRoute
