openapi: 3.0.3
info:
  title: Swagger Food Ordering App - OpenAPI 3.0
  description: |-
    This food ordering system is a digital platform or application that allows users to order food from one restaurants or food establishments for delivery or pickup. It provides a convenient and streamlined process for customers to browse menus, select items, customize orders, and complete transactions.
  contact:
    email: leanhtrung97@gmail.com
  version: 1.0.11
servers:
  - url: http://localhost:1337/api/v1
tags:
  - name: Auth
    description: Login And Register
  - name: Order
    description: Operations about  Orders
  - name: User
    description: Operations about Users
paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: User login
      description: Authenticate and log in a user
      operationId: login
      requestBody:
        description: User credentials for login
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's Email
                  example: leanhtrung97@gmail.com
                password:
                  type: string
                  example: abc123
        required: true
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: 'success'
                    description: Status returned From Server
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        description: Authentication token for the user
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                      refresh_token:
                        type: string
                        description: Token for the refresh access token
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '401':
          description: Login Fail
        '400':
          description: Invalid Input
  /auth/register:
    post:
      tags:
        - Auth
      summary: User register
      description: Authenticate and log in a user
      operationId: register
      requestBody:
        description: User info for register
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's Email
                  example: leanhtrung97@gmail.com
                password:
                  type: string
                  example: abc123
        required: true
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: 
                    type: string
                    example: 'success'
                    description: Status returned From Server
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        description: Authentication token for the user
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
                      refresh_token:
                        type: string
                        description: Token for the refresh access token
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        '401':
          description: Login Fail
        '400':
          description: Invalid Input